version: "3.4"
services:
  code-server:
    image: linuxserver/code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Phoenix
      - FILE__PASSWORD=/run/secrets/vscode_token #optional
      - FILE__SUDO_PASSWORD=/run/secrets/vscode_token #optional
      - DEFAULT_WORKSPACE=/workspace #optional
    volumes:
      - gfs-docker:/workspace
      - vscode:/config
    networks:
      - traefik_internal
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.vscode.entrypoints=websecure"
        - "traefik.http.routers.vscode.tls=true"
        - "traefik.http.routers.vscode.rule=Host(`vscode.docker.tsphotoclicks.net`)"
        - "traefik.http.services.vscode.loadbalancer.server.port=8443"
    restart: unless-stopped
    secrets:
      - vscode_token

secrets:
  vscode_token:
    external: true

volumes:
  vscode:
    driver: glusterfs
    name: "gfs-docker/vscode"
  gfs-docker:
    driver: glusterfs
    name: "gfs-docker"

networks:
  traefik_internal:
    external: true
