version: "3.8"

services:
  grafana:
    image: grafana/grafana
    deploy:
      replicas: 1
      
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.grafana.entrypoints=websecure"
        - "traefik.http.routers.grafana.tls=true"
        - "traefik.http.routers.grafana.rule=Host(`grafana.docker.tsphotoclicks.net`)"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - monitoring
      - traefik_internal

  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--log.level=error'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=7d'
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.prometheus.entrypoints=websecure"
        - "traefik.http.routers.prometheus.tls=true"
        - "traefik.http.routers.prometheus.rule=Host(`prometheus.docker.tsphotoclicks.net`)"
        - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
    restart: unless-stopped
    volumes:
      - prometheus-data:/prometheus
      - prometheus-config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    command: -logtostderr -docker_only
    deploy:
      mode: global
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro                   
    networks:
      - monitoring
  
  node-exporter:
    image: prom/node-exporter
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.ipvs'
    deploy:
      mode: global
    volumes:
      - /:/rootfs:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    networks:
      - monitoring

volumes:
  grafana-data:
    driver: glusterfs
    name: "gfs-docker/grafana-data"
  prometheus-data:
    driver: glusterfs
    name: "gfs-docker/prometheus-data"
  prometheus-config:
    driver: glusterfs
    name: "gfs-docker/prometheus-config"

networks:
  monitoring:
    external: true
  traefik_internal:
    external: true
