version: "3.4"

services:
  traefik:
    image: "traefik:latest"
    networks:
      - traefik_default
    deploy:
      placement:
        constraints: [node.role == manager]
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      # - "--api.dashboard=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik_default"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      
      - "--providers.docker.swarmMode=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      # - traefik:/etc/traefik
      # - traefik-certs:/ssl-certs
      - /var/run/docker.sock:/var/run/docker.sock:ro

# volumes:
#   traefik:
#     driver: glusterfs
#     name: "gfs-docker/traefik"
#   traefik-certs:
#     driver: glusterfs
#     name: "gfs-docker/traefik-certs"

networks:
  traefik_default:
    external: true