version: '3.4'

services:
  nginx:
    image: "nginx:latest"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik_default
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nginx.entrypoints=websecure"
        - "traefik.http.routers.nginx.tls=true"
        - "traefik.http.routers.nginx.rule=Host(`nginx.docker.tsphotoclicks.net`)"
        - "traefik.http.services.nginx.loadbalancer.server.port=80"
        # - "traefik.http.routers.whoami.tls.certresolver=myresolver"

networks:
  traefik_default:
    external: true