version: '3.4'

services:
  nginx:
    image: "nginx:latest"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik_internal
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nginx.entrypoints=websecure"
        - "traefik.http.routers.nginx.tls=true"
        - "traefik.http.routers.nginx.rule=Host(`nginx.docker.tsphotoclicks.net`)"
        - "traefik.http.services.nginx.loadbalancer.server.port=80"

networks:
  traefik_internal:
    external: true