version: "3.4"
services:
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller:latest
    container_name: unifi-controller
    environment:
      - TZ=America/Phoenix
    volumes:
      - unifi-controller:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
    networks:
      - traefik_internal
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.unifi.entrypoints=websecure"
        - "traefik.http.routers.unifi.tls=true"
        - "traefik.http.routers.unifi.rule=Host(`unifi.docker.tsphotoclicks.net`)"
        - "traefik.http.services.unifi.loadbalancer.server.port=80"
        - "traefik.http.services.unifi.loadbalancer.server.scheme=https"
    restart: unless-stopped

volumes:
  unifi-controller:
    driver: glusterfs
    name: "gfs-docker/unifi-controller"

networks:
  traefik_internal:
    external: true