version: "3.4"
services:
  unifi-controller:
    image: linuxserver/unifi-controller:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Phoenix
    volumes:
      - unifi-controller:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 6789:6789
    networks:
      - traefik_internal
      - unifi_net
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.unifi.entrypoints=websecure"
        - "traefik.http.routers.unifi.tls=true"
        - "traefik.http.routers.unifi.rule=Host(`unifi.docker.tsphotoclicks.net`)"
        - "traefik.http.services.unifi.loadbalancer.server.port=8443"
        - "traefik.http.services.unifi.loadbalancer.server.scheme=https"
    restart: unless-stopped

volumes:
  unifi-controller:
    driver: glusterfs
    name: "gfs-docker/unifi-controller"

networks:
  traefik_internal:
    external: true
  unifi_net:
    external: true