version: "3.4"
services:
  unifi-controller:
    image: linuxserver/unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Phoenix
    volumes:
      - unifi-controller:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp
    networks:
      - traefik_internal
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.unifi.entrypoints=websecure"
        - "traefik.http.routers.unifi.tls=true"
        - "traefik.http.routers.unifi.rule=Host(`unifi.docker.tsphotoclicks.net`)"
        - "traefik.http.services.unifi.loadbalancer.server.port=8443"
        - "traefik.http.services.unifi.loadbalancer.server.scheme=https"
    restart: unless-stopped

volumes:
  unifi-controller:
    driver: glusterfs
    name: "gfs-docker/unifi-controller"

networks:
  traefik_internal:
    external: true